### ISSUE TITLE
Consistency issue

### ISSUE THREAD

**Issue by xputerax** [farhan-helmy/CBS-2.0-revamp#1]
Tak konsisten. Semua benda dalam english tapi yang ni dalam BM. Create isu sebab malas nak submit PR

https://github.com/farhan-helmy/CBS-2.0-revamp/blob/a502414b52bc100bed6148ec81aae640ec44e666/app/Models/Appointment.php#L20

https://github.com/farhan-helmy/CBS-2.0-revamp/blob/a502414b52bc100bed6148ec81aae640ec44e666/database/migrations/2021_04_06_143935_create_appointments_table.php#L24

**Comment by farhan-helmy** [comment]
> Tak konsisten. Semua benda dalam english tapi yang ni dalam BM. Create isu sebab malas nak submit PR
> 
> https://github.com/farhan-helmy/CBS-2.0-revamp/blob/a502414b52bc100bed6148ec81aae640ec44e666/app/Models/Appointment.php#L20
> 
> https://github.com/farhan-helmy/CBS-2.0-revamp/blob/a502414b52bc100bed6148ec81aae640ec44e666/database/migrations/2021_04_06_143935_create_appointments_table.php#L24

tq for the review tuan
